### ISSUE TITLE
Unable to parse API response with example of `circleci_build`

### ISSUE THREAD

**Issue by keyolk** [turbot/steampipe-plugin-circleci#12]
**Describe the bug**

With example query, it just puts error like following
```
> select
  username as "organization",
  reponame,
  branch,
  build_time_millis,
  status,
  author_name,
  build_url
from
  circleci_build
where
  status = 'success'
order by
  stop_time desc
limit
  10;

Error: 429: unable to parse API response: invalid character 'R' looking for beginning of value (SQLSTATE HV000)

+--------------+----------+--------+-------------------+--------+-------------+-----------+
| organization | reponame | branch | build_time_millis | status | author_name | build_url |
+--------------+----------+--------+-------------------+--------+-------------+-----------+
+--------------+----------+--------+-------------------+--------+-------------+-----------+
>
```

**Steampipe version (`steampipe -v`)**
```
$ steampipe -v
Steampipe v0.20.10
```

**Plugin version (`steampipe plugin list`)**
```
| hub.steampipe.io/plugins/turbot/circleci@latest   | 0.3.0   | circleci    |
```

**Comment by misraved** [comment]
Welcome to Steampipe @keyolk and apologies for the snag!!

Do you get the above error when trying to run simple queries like `select build_num, build_url, status from circleci_build` or `select * from circleci_build limit 5`?

**Comment by gavin-jeong** [comment]
@misraved Same error with the given query as well : )

**Comment by keyolk** [comment]
@misraved Same error with the query too

**Comment by misraved** [comment]
Thanks @keyolk for the confirmation!

**Comment by misraved** [comment]
Thanks for the input @graza-io 👍, yes let us go ahead and create the relevant issue in the repo for the bug.

**Comment by graza-io** [comment]
Raised: https://github.com/jszwedko/go-circleci/issues/43

**Comment by bigdatasourav** [comment]
We're closing this issue for now; we'll revisit it once the SDK [issue](https://github.com/jszwedko/go-circleci/issues/45) is resolved.
